
networks:
  internal:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-telegram-server
    
    ports:
      - "8080:8080"

    volumes:
      - ./telegrambot:/var/www/php
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/logs/nginx

    depends_on:
      - php

   

    networks:
      - internal


  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile

    container_name: php-telegram-server

    volumes:
      - ./telegrambot:/var/www/php

    networks:
      - internal


  postgresql:
    image: postgres:16.4
    restart: unless-stopped
    shm_size: 256mb

    container_name: postgresql-telegram-server

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: q1w2e3r4t5y6u7i8o9p0
    
    ports:
      - 5432:5432

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    networks:
      - internal


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: q1w2e3r4t5y6u7i8o9p0
      PGADMIN_LISTEN_PORT: 88
    ports:
      - 8090:88
    
    depends_on:
      - postgresql

    networks:
      - internal

